FROM postgres:9.6
MAINTAINER Oleg Venger (farir1881@gmail.com)

USER root

RUN apt-get update &&\
apt-get -y install wget git

RUN wget "https://dl.google.com/go/go1.10.linux-amd64.tar.gz"
RUN tar -C /usr/local -xzf go1.10.linux-amd64.tar.gz &&\
mkdir go && mkdir go/src && mkdir go/bin && mkdir go/pkg
#mkdir -p go/{src,pkg,bin}

ENV GOPATH $HOME/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH &&\
export PATH=$PATH:/usr/local/go/bin

RUN echo "unix_socket_directory = '/var/run/postgresql/'" » /var/lib/postgresql/data/postgresql.conf
RUN sed -i -e 's/^#listen_addresses =.*$/listen_addresses = '*'/' /var/lib/postgresql/data/postgresql.conf
RUN echo "host all all 0.0.0.0/0 md5" » /var/lib/postgresql/data/pg_hba.conf

USER postgres
ENV PGVER 9.6

ADD ./ $GOPATH/src/go_tp_db/
EXPOSE 5000
WORKDIR $GOPATH/src/go_tp_db
#RUN echo "host all all 0.0.0.0/0 md5" » /etc/postgresql/$PGVER/main/pg_hba.conf
USER root

CMD go run main.go
#service postgresql start && psql —command "CREATE DATABASE tpdb" &&